networks:
  frontend:
  backend:

volumes:
  node:
  db-data:

services:
  front:
    build:
      context: .
      dockerfile: ./docker/local/node/Dockerfile
    container_name: front
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - ./logs/front:/root/.npm/_logs
      - node:/app/node_modules
    # Docker 内で Vite を `npm run dev` してもアクセスできるようにする
    command: npm run dev -- --host
    stdin_open: true
    tty: true
    networks:
      - frontend
  db:
    image: mysql:8.3
    container_name: db
    ports:
      - 3306:3306
    # パスワードで mysql にログインできるようにする
    command: --authentication_policy=mysql_native_password
    environment:
      - MYSQL_DATABASE=study_vue3
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      # タイムゾーンを 東京 にする
      - TZ=Asia/Tokyo
    volumes:
      - ./logs/db:/var/log/mysql
      - ./docker/local/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/local/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
      - db-data:/var/lib/mysql
    networks:
      - backend
