SET NAMES utf8mb4;

INSERT IGNORE INTO `users` (`id`, `account_name`, `password`, `name`) VALUES
(UUID(), 'admin', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'システム管理者'),
(UUID(), 'author1', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー1'),
(UUID(), 'author2', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー2'),
(UUID(), 'author3', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー3'),
(UUID(), 'author4', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー4'),
(UUID(), 'author5', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー5'),
(UUID(), 'author6', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー6'),
(UUID(), 'author7', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー7'),
(UUID(), 'author8', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー8'),
(UUID(), 'author9', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー9'),
(UUID(), 'author10', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー10'),
(UUID(), 'author11', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー11'),
(UUID(), 'author12', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー12'),
(UUID(), 'author13', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー13'),
(UUID(), 'author14', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー14'),
(UUID(), 'author15', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー15'),
(UUID(), 'author16', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー16'),
(UUID(), 'author17', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー17'),
(UUID(), 'author18', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー18'),
(UUID(), 'author19', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー19'),
(UUID(), 'author20', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー20'),
(UUID(), 'author21', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー21'),
(UUID(), 'author22', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー22'),
(UUID(), 'author23', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー23'),
(UUID(), 'author24', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー24'),
(UUID(), 'author25', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー25'),
(UUID(), 'author26', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー26'),
(UUID(), 'author27', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー27'),
(UUID(), 'author28', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー28'),
(UUID(), 'author29', '$2a$10$9ZINRSZaIH9phktmAhxACeQETQreIYMYXoWiqSljMaa.jKzNuJsO6', 'ユーザー29');
